DROP DATABASE IF EXISTS DOCTORAL;
CREATE DATABASE DOCTORAL;
USE DOCTORAL;


-- PART 1 Solution

DROP TABLE IF EXISTS INSTRUCTOR;
DROP TABLE IF EXISTS TT;
DROP TABLE IF EXISTS PHDSTUDENT;
DROP TABLE IF EXISTS GTA;
DROP TABLE IF EXISTS GRA;
DROP TABLE IF EXISTS SELFSUPPORT;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS COURSESTAUGHT;
DROP TABLE IF EXISTS MILESTONE;
DROP TABLE IF EXISTS MILESTONESPASSED;
DROP TABLE IF EXISTS GRANTS;
DROP TABLE IF EXISTS GRANTSASSOCIATED;
DROP TABLE IF EXISTS PHDCOMMITTEE;
DROP TABLE IF EXISTS GRANTSASSOCIATED;
DROP TABLE IF EXISTS PHDCOMMITTEE;

CREATE TABLE INSTRUCTOR(  
    InstructorId CHAR(10) NOT NULL PRIMARY KEY,  
    Fname VARCHAR(25) NOT NULL,
    Lname VARCHAR(25) NOT NULL,
    StartDate DATE,
    Degree CHAR(12),
    Rank CHAR(12),
    Type CHAR(10)
);

CREATE TABLE TT(
    InstructorId CHAR(10) NOT NULL PRIMARY KEY,
    NoOfPhDStudents INT NOT NULL,
    FOREIGN KEY(InstructorId) REFERENCES INSTRUCTOR(InstructorId)


);
CREATE TABLE PHDSTUDENT(
    StudentId CHAR(10) NOT NULL PRIMARY KEY,
    FName VARCHAR(25) NOT NULL,
    Lname VARCHAR(25) NOT NULL,
    StSem CHAR (10) NOT NULL,
    StYear CHAR(5) NOT NULL,
    Supervisor CHAR(10)

    
);
--     FOREIGN KEY(Supervisor) REFERENCES INSTRUCTOR(InstructorId)

CREATE TABLE COURSE (
    CourseId CHAR(10) NOT NULL PRIMARY KEY , 
    CName CHAR(100)
);

CREATE TABLE SECTION (
    SectionId CHAR(10) NOT NULL PRIMARY KEY , 
    CourseId CHAR(10),
     FOREIGN KEY(CourseId) REFERENCES COURSE(CourseId)

);

CREATE TABLE GTA(
    SectionId CHAR(10),
    MonthlyPay INT,
    StudentId CHAR(10) NOT NULL PRIMARY KEY,
    FOREIGN KEY(SectionId) REFERENCES SECTION(SectionId),
	 FOREIGN KEY(StudentId) REFERENCES PHDSTUDENT(StudentId)

    
);


CREATE TABLE GRA(
    StudentId CHAR(10) NOT NULL PRIMARY KEY,
    Funding CHAR(10),
    MonthlyPay INT,
    FOREIGN KEY(StudentId) REFERENCES PHDSTUDENT(StudentId)

);



CREATE TABLE SELFSUPPORT (
 StudentId CHAR(10) NOT NULL PRIMARY KEY,
 FOREIGN KEY(StudentId) REFERENCES PHDSTUDENT(StudentId)

);



CREATE TABLE SCHOLARSHIPSUPPORT (
    StudentId CHAR(10) NOT NULL PRIMARY KEY,
    Type CHAR(10) NOT NULL,
    Source CHAR(10),
    FOREIGN KEY(StudentId) REFERENCES PHDSTUDENT(StudentId)

    );


CREATE TABLE COURSESTAUGHT (
    CourseId CHAR(10) NOT NULL, 
    InstructorId CHAR(10) NOT NULL,
    PRIMARY KEY(CourseId , InstructorId),
    FOREIGN KEY(CourseId) REFERENCES COURSE(CourseId),
    FOREIGN KEY(InstructorId) REFERENCES INSTRUCTOR(InstructorId)

);

    

CREATE TABLE MILESTONE (
    MID CHAR(10) NOT NULL PRIMARY KEY, 
    MName CHAR(100)
);

CREATE TABLE MILESTONESPASSED (
    StudentId CHAR(10) NOT NULL,
    MId CHAR(10) NOT NULL, 
    PassDate DATE,
    PRIMARY KEY(StudentId, MID),
    FOREIGN KEY(StudentId) REFERENCES PHDSTUDENT(StudentId),
    FOREIGN KEY(MId) REFERENCES MILESTONE(MID)

);

    

CREATE TABLE GRANTS (
    AccountNo CHAR(10) NOT NULL PRIMARY KEY, 
    Type CHAR(10),
    GrantTitle CHAR(10),
    Source CHAR(10),
    StDate DATE,
    EndDate DATE,
    StAmount INT,
    CurrentBalance INT
);


CREATE TABLE GRANTSASSOCIATED(
    AccountNo CHAR(10) NOT NULL,
    InstructorId CHAR(10) NOT NULL,
    PIType CHAR(15),
    PRIMARY KEY(AccountNo,InstructorID),
    FOREIGN KEY(InstructorId) REFERENCES INSTRUCTOR(InstructorId)

);
   



CREATE TABLE PHDCOMMITTEE(
    StudentId CHAR(10) NOT NULL,
    InstructorId CHAR(10) NOT NULL,
    PRIMARY KEY(StudentId,InstructorId),--    FOREIGN KEY(InstructorId) REFERENCES INSTRUCTOR(InstructorId),
    FOREIGN KEY(StudentId) REFERENCES PHDSTUDENT(StudentId)
    

);









/* Loads the dataset form the provided txt files into the database           */   
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_Instructor.txt' INTO TABLE INSTRUCTOR FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_PhDStudent.txt' INTO TABLE PHDSTUDENT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_Course.txt' INTO TABLE Course FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_CoursesTaught.txt' INTO TABLE COURSESTAUGHT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_GRA.txt' INTO TABLE GRA FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_GTA.txt' INTO TABLE GTA FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_Grants.txt' INTO TABLE GRANTS FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_GrantAssociated.txt' INTO TABLE GRANTSASSOCIATED FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_Milestone.txt' INTO TABLE MILESTONE FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_MilestonesPassed.txt' INTO TABLE MILESTONESPASSED FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_PhDCommittee.txt' INTO TABLE PHDCOMMITTEE FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_ScholarshipSupport.txt' INTO TABLE SCHOLARSHIPSUPPORT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_Section.txt' INTO TABLE SECTION FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_SelfSupport.txt' INTO TABLE SELFSUPPORT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'C:/Users/alvin/OneDrive/Other/Desktop/Dataset/Dataset/_TT.txt' INTO TABLE TT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;




/*
SELECT * FROM INSTRUCTOR;
SELECT * FROM TT;
SELECT * FROM PHDSTUDENT;
SELECT * FROM GTA;
SELECT * FROM GRA;
SELECT * FROM SELFSUPPORT;
SELECT * FROM COURSE;
SELECT * FROM SECTION;
SELECT * FROM COURSESTAUGHT;
SELECT * FROM MILESTONE;
SELECT * FROM MILESTONESPASSED;
SELECT * FROM GRANTS;
SELECT * FROM GRANTSASSOCIATED;
SELECT * FROM PHDCOMMITTEE;
SELECT * FROM GRANTSASSOCIATED;
SELECT * FROM PHDCOMMITTEE;
*/

SELECT * FROM INSTRUCTOR;
SELECT * FROM PHDSTUDENT;
SELECT * FROM PHDCOMMITTEE;

SELECT * FROM COURSESTAUGHT;

-- PART 2 SUBPART 1

CREATE VIEW SUPERVISION_INFO(IID, IFName, ILName,SId, SFName , SLName , SStSem , SStYear)
AS SELECT INSTRUCTOR.InstructorId, INSTRUCTOR.FName,INSTRUCTOR.LName, PHDSTUDENT.StudentId, PHDSTUDENT.FName, PHDSTUDENT.LName, PHDSTUDENT.StSem, PHDSTUDENT.StYear
	FROM	INSTRUCTOR , PHDSTUDENT
	WHERE	INSTRUCTOR.InstructorId = PHDSTUDENT.Supervisor;

SELECT * FROM SUPERVISION_INFO;



-- PART 2 SUBPART 2

-- A







